# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_all_identifiers.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_all_identifiers.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18pb_all_identifiers.proto\x1a\x0cnanopb.proto*z\n\x10pb_device_type_e\x12\x15\n\x11\x44\x45VICE_TYPE__NONE\x10\x00\x12*\n%DEVICE_TYPE__BOTTLECRUSHER_CONTROLLER\x10\x80\x02\x12#\n\x1e\x44\x45VICE_TYPE__BOTTLECRUSHER_SSR\x10\x80\x04*M\n\x12pb_protocol_type_e\x12\x17\n\x13PROTOCOL_TYPE__NONE\x10\x00\x12\x1e\n\x19PROTOCOL_TYPE__BOOTLOADER\x10\x80\x02\x62\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])

_PB_DEVICE_TYPE_E = _descriptor.EnumDescriptor(
  name='pb_device_type_e',
  full_name='pb_device_type_e',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE__NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE__BOTTLECRUSHER_CONTROLLER', index=1, number=256,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE__BOTTLECRUSHER_SSR', index=2, number=512,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=42,
  serialized_end=164,
)
_sym_db.RegisterEnumDescriptor(_PB_DEVICE_TYPE_E)

pb_device_type_e = enum_type_wrapper.EnumTypeWrapper(_PB_DEVICE_TYPE_E)
_PB_PROTOCOL_TYPE_E = _descriptor.EnumDescriptor(
  name='pb_protocol_type_e',
  full_name='pb_protocol_type_e',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_TYPE__NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTOCOL_TYPE__BOOTLOADER', index=1, number=256,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=166,
  serialized_end=243,
)
_sym_db.RegisterEnumDescriptor(_PB_PROTOCOL_TYPE_E)

pb_protocol_type_e = enum_type_wrapper.EnumTypeWrapper(_PB_PROTOCOL_TYPE_E)
DEVICE_TYPE__NONE = 0
DEVICE_TYPE__BOTTLECRUSHER_CONTROLLER = 256
DEVICE_TYPE__BOTTLECRUSHER_SSR = 512
PROTOCOL_TYPE__NONE = 0
PROTOCOL_TYPE__BOOTLOADER = 256


DESCRIPTOR.enum_types_by_name['pb_device_type_e'] = _PB_DEVICE_TYPE_E
DESCRIPTOR.enum_types_by_name['pb_protocol_type_e'] = _PB_PROTOCOL_TYPE_E
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
