/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PB_ALL_IDENTIFIERS_PB_H_INCLUDED
#define PB_PB_ALL_IDENTIFIERS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _pb_device_type_e { 
    pb_device_type_e_DEVICE_TYPE__NONE = 0, 
    pb_device_type_e_DEVICE_TYPE__BOTTLECRUSHER_CONTROLLER = 256, 
    pb_device_type_e_DEVICE_TYPE__BOTTLECRUSHER_SSR = 512 
} pb_device_type_e;

typedef enum _pb_protocol_type_e { 
    pb_protocol_type_e_PROTOCOL_TYPE__NONE = 0, 
    pb_protocol_type_e_PROTOCOL_TYPE__BOOTLOADER = 256 
} pb_protocol_type_e;

/* Helper constants for enums */
#define _pb_device_type_e_MIN pb_device_type_e_DEVICE_TYPE__NONE
#define _pb_device_type_e_MAX pb_device_type_e_DEVICE_TYPE__BOTTLECRUSHER_SSR
#define _pb_device_type_e_ARRAYSIZE ((pb_device_type_e)(pb_device_type_e_DEVICE_TYPE__BOTTLECRUSHER_SSR+1))

#define _pb_protocol_type_e_MIN pb_protocol_type_e_PROTOCOL_TYPE__NONE
#define _pb_protocol_type_e_MAX pb_protocol_type_e_PROTOCOL_TYPE__BOOTLOADER
#define _pb_protocol_type_e_ARRAYSIZE ((pb_protocol_type_e)(pb_protocol_type_e_PROTOCOL_TYPE__BOOTLOADER+1))


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
